apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: skyline
  description: Enables basic auth smtp with ms graph
spec:
  type: service
  lifecycle: production
  owner: SKIP
  system: SKIP
