name: Build and test PR

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
          check-latest: true
      - uses: actions/cache@v3 # ratchet:actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build binary
        run: |
          go build
      - name: Run tests
        run: |
          go test ./...
